---
title: "Dashboard for Instacart Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)


# add data
set.seed(1)
data(instacart)
instacart_dat = 
  instacart %>%  
  mutate(order_dow = ordered(order_dow, levels = c(0:6), 
                             labels = c("Sunday", "Monday", "Tuesday", "Wednesday", 
                                        "Thursday", "Friday", "Saturday"))) %>% 
  sample_n(5000)

# common aisle - top 8
common_aisles_1 = 
  instacart_dat %>% 
  count(aisle, sort = TRUE) %>% 
  top_n(8) %>% 
  select(aisle)

# common aisle - top 10
common_aisles_2 = 
  instacart_dat %>% 
  count(aisle, sort = TRUE) %>% 
  top_n(10) %>% 
  select(aisle)
```

Row {data-width=650}
-----------------------------------------------------------------------

### "Add to cart order" over the course of 24 hours for top 8 aisles

```{r, echo=FALSE}
inner_join(instacart_dat, common_aisles_1, by = "aisle") %>% 
  plot_ly(y = ~add_to_cart_order, x = ~order_hour_of_day, color = ~aisle, type = "scatter",  mode = "markers", text = ~product_name)

```

Row {data-width=350}
-----------------------------------------------------------------------

### Mean orders from each aisle

```{r, echo=FALSE}
inner_join(instacart_dat, common_aisles_2, by = "aisle") %>% 
  mutate(aisle = fct_reorder(aisle, order_id)) %>% 
  plot_ly(y = ~order_id, color = ~aisle, type = "box",
          colors = "Set2")
```

### Which day has the most orders?

```{r, echo=FALSE}
instacart_dat %>% 
  count(order_dow) %>% 
  mutate(order_dow = fct_reorder(order_dow, n)) %>% 
  plot_ly(x = ~order_dow, y = ~n, color = ~order_dow, type = "bar")
```

